service: node-matchmake

provider:
  name: aws
  runtime: nodejs20.x
  versionFunctions: false # removes the previous saved lambda functio
  stage: "dev" # diff staging like prod, qa, stage
  region: us-east-1
  apiGateway:
    restApiId:
      "Fn::ImportValue": SharedGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": SharedGW-rootResourceId
  httpApi:
    cors: true
    # payload: "2.0"
    # disableDefaultEndpoint: false
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource: "*"

functions:
  app:
    handler: src/handler.handler
    environment:
      NODE_ENV: prod
    events:
      - http:
          path: /items
          method: any
      - http:
          path: /items/{id}
          method: get
      - http:
          path: /items/{id}
          method: put
      - http:
          path: /items/{id}
          method: delete
      - http:
          path: /user/signup
          method: post
      - http:
          path: /user/login
          method: post

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  dotenv:
    path: .env
